[package]
name = "yolol-runner"
version = "0.2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"yolol-devices" = {git = 'https://github.com/wolfnether/yolol-devices'}
"peg" = "0.7.0"